### ISSUE TITLE
The name "module" is confusing

### ISSUE THREAD

**Issue by Hiroki-Harata-sti** [SIOS-Technology-Inc/dacrane#33]
The name "module" conjures up the image of a concrete entity, which makes it difficult to convey that it is an abstract entity.

Since a module is a pair of the current instance, we would like to devise a name for both. For example, the following are candidates.

1. module <-> instance (current)
2. class <-> instance (OOP like)

**Comment by t-ikeda-sti** [comment]
* model <-> instance
* template <-> instance

**Comment by t-ikeda-sti** [comment]
@Hiroki-Harata-sti Thank you for your suggestion.
It was decided to continue using the term `module`.
The `class` term took into account the possibility that object-oriented thinking may adversely impede understanding. We felt that `module` term was an equivalent term to existing IaC tools such as terraform and ansible, and would lower the barrier of entry for users of other tools when migrating.
